# Secrets configuration for Health Insights Agent
# Replace placeholder values with your actual credentials.

# Groq API key for AI model access
GROQ_API_KEY = "enter-your-groq-api-key"

# Supabase database credentials
SUPABASE_URL = "enter-your-supabase-url"
SUPABASE_KEY = "enter-your-supabase-key"
